### ISSUE TITLE
Line 63 NoneType error

### ISSUE THREAD

**Issue by AlexOConnorHub** [nametable/sau-daily-survey-bot#3]
![Screenshot_20210321-230800.png](https://user-images.githubusercontent.com/43659595/111935711-6e983e80-8a9a-11eb-9d08-940b1155a097.png) I haven't looked into what the problem is, I just noticed it didn't work the past couple days, so I ran the script and got this error.

**Comment by nametable** [comment]
Oof, I will have to take a look.

Thanks for your report!

**Comment by nametable** [comment]
I just tried the script and I did not experience the same error...
```
Status code:   200
Authentication Complete :) In theory successfully too :)
Survey Params to Submit
{   'Answers.Index': '6',
    'Answers[2].Answer': 'No',
    'Answers[2].QuestionID': '2',
    'Answers[4].Answer': 'No',
    'Answers[4].QuestionID': '4',
    'Answers[5].Answer': 'No',
    'Answers[5].QuestionID': '5',
    'Answers[6].Answer': 'No',
    'Answers[6].QuestionID': '6',
    'Answers[7].Answer': 'No',
    'Answers[7].QuestionID': '7',
    'PersonID': '********'}
Status code:   200
Now on page https://www.southern.edu/safety/
```

**Comment by AlexOConnorHub** [comment]
Commenting out line 63 causes an error in the previous line. If both lines are commented out, it complains about a missing scheme.
________________________________

**Comment by AlexOConnorHub** [comment]
... Just remembered I changed my password... Ignore this, it's late at night and I'm not thinking through everything.
